{
 "title": "Drudge",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "# Links Processed ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history "
    }
   ]
  },
  {
   "title": "# UnChanging Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where perm_link = TRUE "
    }
   ]
  },
  {
   "title": "Departed Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where departed = TRUE "
    }
   ]
  },
  {
   "title": "# Changable Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where perm_link = FALSE and departed = FALSE "
    }
   ]
  },
  {
   "title": "Departed Links Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(latest_dt) AS date_portion, count(*) as departed_links_per_day from  scraper_history where perm_link = false and departed = TRUE group by DATE(latest_dt) order by DATE(latest_dt) "
    }
   ]
  },
  {
   "title": "Links Added Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(first_dt) AS date_portion, count(*) as links_per_day from  scraper_history where perm_link = false group by DATE(first_dt) order by DATE(first_dt) "
    }
   ]
  },
  {
   "title": "Avg Link Duration Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(first_dt) AS date_portion, count(*) as links_per_day, round((avg(duration_secs) / 3600),1) as avg_duration_hours from  scraper_history where perm_link = false group by DATE(first_dt) order by DATE(first_dt) "
    }
   ]
  },
  {
   "title": "Current Links (DM)",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 5 },
   "options": {
    "content": "| Line | Line Content | Duration | Site Name | First Date | Latest Date | id |\n| ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| {{line_num}} | <a href=\"{{line_url}}\">{{line_content}}</a> | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT id, line_num, line_content, line_url, duration_txt, site_name_txt, first_dt, latest_dt FROM scraper_history where perm_link = FALSE and departed = FALSE and id not in (120733, 118834) order by line_num "
    }
   ]
  },
  {
   "title": "Departed Links",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": {
    "content": "| Line | Line Content | Duration | Site Name | First Date | Latest Date | id |\n| ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| {{line_num}} | <a href=\"{{line_url}}\">{{line_content}}</a> | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT id, line_num, line_content, line_url, duration_txt, site_name_txt, first_dt, latest_dt FROM scraper_history where departed = TRUE and id not in (118953,111279,109982,110410,109859,106468,98913,88184,72026,54312,58396,57534,33717,37509,38304,38088,37294,16196,16134,16794,2691,2784,233,144) order by latest_dt desc"
    }
   ]
  },
  {
   "title": "Rarely Changing Links",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "options": {
    "content": "| Line | Line Content | Duration | Site Name | First Date | Latest Date | id |\n| ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| {{line_num}} | <a href=\"{{line_url}}\">{{line_content}}</a> | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT line_num, line_content, line_url, duration_txt, id, site_name_txt, first_dt, latest_dt FROM scraper_history where perm_link = TRUE order by line_num"
    }
   ]
  }
 ]
}