{
 "title": "Drudge",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "# Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history "
    }
   ]
  },
  {
   "title": "# Changable Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where perm_link = FALSE and departed = FALSE "
    }
   ]
  },
  {
   "title": "# UnChanging Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where perm_link = TRUE "
    }
   ]
  },
  {
   "title": "Avg Link Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history LIMIT 50 "
    }
   ]
  },
  {
   "title": "Avg Links Per Day",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history "
    }
   ]
  },
  {
   "title": "Current Links",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT line_num, line_content, line_url, first_dt, latest_dt, line_type FROM scraper_history where perm_link = FALSE and departed = FALSE order by line_num "
    }
   ]
  },
  {
   "title": "Departed Links",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT line_num, line_content, line_url, first_dt, latest_dt, line_type FROM scraper_history where departed = TRUE  order by line_num"
    }
   ]
  },
  {
   "title": "Rarely Changing Links",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT line_num, line_content, line_url, first_dt, latest_dt, line_type FROM scraper_history where perm_link = TRUE order by line_num"
    }
   ]
  }
 ]
}