{
 "title": "Drudge",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "# Links Processed ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history "
    }
   ]
  },
  {
   "title": "# UnChanging Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where perm_link = TRUE "
    }
   ]
  },
  {
   "title": "Departed Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where departed = TRUE "
    }
   ]
  },
  {
   "title": "# Changable Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where perm_link = FALSE and departed = FALSE "
    }
   ]
  },
  {
   "title": "Departed Links Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(latest_dt) AS date_portion, count(*) as departed_links_per_day from  scraper_history where perm_link = false and departed = TRUE group by DATE(latest_dt) order by DATE(latest_dt) "
    }
   ]
  },
  {
   "title": "Links Added Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(first_dt) AS date_portion, count(*) as links_per_day from  scraper_history where perm_link = false group by DATE(first_dt) order by DATE(first_dt) "
    }
   ]
  },
  {
   "title": "Avg Link Duration Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(first_dt) AS date_portion, count(*) as links_per_day, round((avg(duration_secs) / 3600),1) as avg_duration_hours from  scraper_history where perm_link = false group by DATE(first_dt) order by DATE(first_dt) "
    }
   ]
  },
  {
   "title": "Latest Scrape",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH time_zone_info AS (\n  SELECT \n    CASE\n      WHEN (SELECT current_setting('TIMEZONE') = 'America/New York') \n           AND (SELECT abbrev FROM pg_timezone_names WHERE name = 'America/New York' LIMIT 1) = 'EST'\n      THEN 'EST'\n      ELSE 'EDT'\n    END AS timezone_status\n)\nSELECT \n      -- timezone_status,\n      -- TO_CHAR(latest_dt AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') as utc_latest_dt,\n      max(TO_CHAR(latest_dt AT TIME ZONE 'UTC' AT TIME ZONE time_zone_info.timezone_status, 'YYYY-MM-DD HH24:MI')) as \"latest scrape\"\nFROM scraper_history, time_zone_info\nwhere departed = false \ngroup by latest_dt\norder by latest_dt desc\n\n"
    }
   ]
  },
  {
   "title": "Current Links",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 35, "w": 12, "x": 0, "y": 5 },
   "options": {
    "content": "| Line Content | Ver | Duration | Site Name | First Date | Latest Date | Line | id |\n| ----- | ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| <a href=\"{{line_url}}\">{{line_content}}</a> | {{ver}} | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{line_num}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "WITH time_zone_info AS (\n  SELECT \n    CASE\n      WHEN (SELECT current_setting('TIMEZONE') = 'America/New York') \n           AND (SELECT abbrev FROM pg_timezone_names WHERE name = 'America/New York' LIMIT 1) = 'EST'\n      THEN 'EST'\n      ELSE 'EDT'\n    END AS timezone_status\n)\nSELECT timezone_status,\n      TO_CHAR(latest_dt AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') as utc_latest_dt,\n      TO_CHAR(first_dt AT TIME ZONE 'UTC' AT TIME ZONE time_zone_info.timezone_status, 'YYYY-MM-DD HH24:MI') as first_dt,\n      TO_CHAR(latest_dt AT TIME ZONE 'UTC' AT TIME ZONE time_zone_info.timezone_status, 'YYYY-MM-DD HH24:MI') as latest_dt,\n      id, \n      line_num, \n      regexp_replace(line_content, E'\\\\r\\\\n|\\\\r|\\\\n', ' ', 'g') as line_content, \n      (select count(*) from scraper_history sh2 where sh2.line_url = scraper_history.line_url) as ver,\n      line_url, duration_txt, site_name_txt \nFROM scraper_history, time_zone_info\nwhere perm_link = FALSE \nand departed = FALSE \norder by duration_txt, line_num \n-- order by ver desc, duration_txt, line_num \n"
    }
   ]
  },
  {
   "title": "Added and Departed Links per day",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_portion::text as date_portion,\n  links_per_day,\n  departed_num\nFROM (\n  SELECT\n    DATE(first_dt) AS date_portion,\n    COUNT(*) AS links_per_day\n  FROM scraper_history\n  WHERE perm_link = false\n  GROUP BY DATE(first_dt)\n) AS links\nJOIN (\n  SELECT\n    DATE(latest_dt) AS departed_date,\n    COUNT(*) AS departed_num\n  FROM scraper_history\n  WHERE perm_link = false AND departed = TRUE\n  GROUP BY DATE(latest_dt)\n) AS departures ON links.date_portion = departures.departed_date\nORDER BY links.date_portion\n"
    }
   ]
  },
  {
   "title": "Recent Departed Links per day",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "rawSql": "select DATE(latest_dt)::text AS departed_date, count(*) as departed_num from  scraper_history where perm_link = false and departed = TRUE group by DATE(latest_dt) order by DATE(latest_dt) desc limit 8;\n"
    }
   ]
  },
  {
   "title": "Most Popular Site Names",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "select site_name_txt as site_name, count(*) as num_count\nfrom  scraper_history\nwhere length(site_name_txt) > 0\ngroup by site_name_txt\norder by count(*) desc\nlimit 20"
    }
   ]
  },
  {
   "title": "Departed Links",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 24 },
   "options": {
    "content": "| Line Content | Ver | Duration | Site Name | First Date | Latest Date | Line | id |\n| ----- | ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| <a href=\"{{line_url}}\">{{line_content}}</a> | {{ver}} | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{line_num}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "WITH time_zone_info AS (\n  SELECT \n    CASE\n      WHEN (SELECT current_setting('TIMEZONE') = 'America/New York') \n           AND (SELECT abbrev FROM pg_timezone_names WHERE name = 'America/New York' LIMIT 1) = 'EST'\n      THEN 'EST'\n      ELSE 'EDT'\n    END AS timezone_status\n)\nSELECT timezone_status,\n      TO_CHAR(latest_dt AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') as utc_latest_dt,\n      TO_CHAR(first_dt AT TIME ZONE 'UTC' AT TIME ZONE time_zone_info.timezone_status, 'YYYY-MM-DD HH24:MI') as first_dt,\n      TO_CHAR(latest_dt AT TIME ZONE 'UTC' AT TIME ZONE time_zone_info.timezone_status, 'YYYY-MM-DD HH24:MI') as latest_dt,\n      id, \n      line_num, \n      regexp_replace(line_content, E'\\\\r\\\\n|\\\\r|\\\\n', ' ', 'g') as line_content, \n      (select count(*) from scraper_history sh2 where sh2.line_url = scraper_history.line_url) as ver,\n      line_url, duration_txt, site_name_txt \nFROM scraper_history, time_zone_info\nwhere departed = TRUE and id not in (109859) \norder by latest_dt desc, line_num asc\n"
    }
   ]
  },
  {
   "title": "Rarely Changing Links",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "options": {
    "content": "| Line | Line Content | Duration | Site Name | First Date | Latest Date | id |\n| ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| {{line_num}} | <a href=\"{{line_url}}\">{{line_content}}</a> | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT line_num, line_content, line_url, duration_txt, id, site_name_txt, TO_CHAR(first_dt, 'YYYY-MM-DD HH24:MI') as first_dt, TO_CHAR(latest_dt, 'YYYY-MM-DD HH24:MI') as latest_dt FROM scraper_history where perm_link = TRUE order by line_num\n"
    }
   ]
  }
 ]
}