{
 "title": "Drudge",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "# Links Processed ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history "
    }
   ]
  },
  {
   "title": "# UnChanging Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where perm_link = TRUE "
    }
   ]
  },
  {
   "title": "Departed Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where departed = TRUE "
    }
   ]
  },
  {
   "title": "# Changable Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scraper_history where perm_link = FALSE and departed = FALSE "
    }
   ]
  },
  {
   "title": "Departed Links Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(latest_dt) AS date_portion, count(*) as departed_links_per_day from  scraper_history where perm_link = false and departed = TRUE group by DATE(latest_dt) order by DATE(latest_dt) "
    }
   ]
  },
  {
   "title": "Links Added Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(first_dt) AS date_portion, count(*) as links_per_day from  scraper_history where perm_link = false group by DATE(first_dt) order by DATE(first_dt) "
    }
   ]
  },
  {
   "title": "Avg Link Duration Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE(first_dt) AS date_portion, count(*) as links_per_day, round((avg(duration_secs) / 3600),1) as avg_duration_hours from  scraper_history where perm_link = false group by DATE(first_dt) order by DATE(first_dt) "
    }
   ]
  },
  {
   "title": "Recent Departed Links per day",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "rawSql": "select DATE(latest_dt)::text AS departed_date, count(*) as departed_num from  scraper_history where perm_link = false and departed = TRUE group by DATE(latest_dt) order by DATE(latest_dt) limit 8;\n"
    }
   ]
  },
  {
   "title": "Current Links (DM)",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 28, "w": 12, "x": 0, "y": 5 },
   "options": {
    "content": "| Line | Line Content | Duration | Site Name | First Date | Latest Date | id |\n| ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| {{line_num}} | <a href=\"{{line_url}}\">{{line_content}}</a> | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT id, \n      line_num, \n      regexp_replace(line_content, E'\\\\r\\\\n|\\\\r|\\\\n', ' ', 'g') as line_content, \n      line_url, duration_txt, site_name_txt, \n      TO_CHAR(first_dt, 'YYYY-MM-DD HH24:MI') as first_dt,\n      TO_CHAR(latest_dt, 'YYYY-MM-DD HH24:MI') as latest_dt\nFROM scraper_history \nwhere perm_link = FALSE \nand departed = FALSE \norder by line_num \n"
    }
   ]
  },
  {
   "title": "Departed Links",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 5 },
   "options": {
    "content": "| Line | Line Content | Duration | Site Name | First Date | Latest Date | id |\n| ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| {{line_num}} | <a href=\"{{line_url}}\">{{line_content}}</a> | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT id, line_num, regexp_replace(line_content, E'\\\\r\\\\n|\\\\r|\\\\n', ' ', 'g') as line_content, line_url, duration_txt, site_name_txt, TO_CHAR(first_dt, 'YYYY-MM-DD HH24:MI') as first_dt, TO_CHAR(latest_dt, 'YYYY-MM-DD HH24:MI') as latest_dt FROM scraper_history where departed = TRUE order by latest_dt desc, line_num asc\n"
    }
   ]
  },
  {
   "title": "Rarely Changing Links",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "options": {
    "content": "| Line | Line Content | Duration | Site Name | First Date | Latest Date | id |\n| ----- | ----- | ------ | ---- | ---- | ---- | ---- |\n{{#each data}}\n| {{line_num}} | <a href=\"{{line_url}}\">{{line_content}}</a> | {{duration_txt}} | {{site_name_txt}} | {{first_dt}} | {{latest_dt}} | {{id}} |\n{{/each}}\n"
   },
   "targets": [
    {
     "rawSql": "SELECT line_num, line_content, line_url, duration_txt, id, site_name_txt, TO_CHAR(first_dt, 'YYYY-MM-DD HH24:MI') as first_dt, TO_CHAR(latest_dt, 'YYYY-MM-DD HH24:MI') as latest_dt FROM scraper_history where perm_link = TRUE order by line_num\n"
    }
   ]
  }
 ]
}