name: Python Script

on:
  schedule:
    - cron: "0,30 11-23 * * *"
    - cron: "0,30 0-2 * * *"
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run connection test
        env:
          SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scrapers/neon-connect2.py

      - name: Run scraper
        env:
          SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scrapers/scraper.py

      - name: Run updates of booleans and duration fields
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scrapers/run-updates.py
