name: Python Script

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run connection test
        env:
          SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scrapers/neon-connect2.py

      - name: Run scraper
        env:
          SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scrapers/scraper.py

      - name: Run updates of booleans and duration fields
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scrapers/run-updates.py
